'use client';
import { useState } from 'react';
type Tab='Übersicht'|'Kampf'|'Zauber'|'Inventar'|'Notizen';
const tabs:[string,string,Tab][]=[['♜','Stats','Übersicht'],['⚔','Waffen','Kampf'],['♨','Items','Inventar'],['▤','Zauber','Zauber'],['♞','Können','Übersicht'],['▥','Story','Notizen']];
export default function LandingTablet({onNavigate}:{onNavigate:(tab:Tab)=>void}){
 const[notice,setNotice]=useState('');
 const rest=(kind:'short'|'long')=>{if(kind==='long'){let data:Record<string,number>={};try{data=JSON.parse(localStorage.getItem('thartos-tablet-stats')||'{}')}catch{}const hpMax=data.hpMax??29;const tempHpMax=data.tempHpMax??5;localStorage.setItem('thartos-tablet-stats',JSON.stringify({...data,hpMax,hp:hpMax,tempHpMax,tempHp:tempHpMax}));setNotice(`Lange Rast: TP ${hpMax}/${hpMax}, temporäre TP ${tempHpMax}`)}else setNotice('Kurze Rast vorgemerkt – Regeln folgen später.');window.setTimeout(()=>setNotice(''),3200)};
 return <main className="tabletLanding"><img className="landingArt" src="/thartos-startseite.png" alt="Thartos kämpft in einer nächtlichen Stadt gegen Untote"/><div className="landingVeil"/><header className="landingNav"><div className="landingTitle"><span>♜</span><b>THARTOS</b></div>{tabs.map(([icon,label,target])=><button key={label} onClick={()=>onNavigate(target)}><span>{icon}</span>{label}</button>)}<button aria-label="Einstellungen">⚙</button></header><section className="landingIdentity"><span>CHARAKTER</span><h1>THARTOS</h1><p>Mensch-Paladin · Stufe 3</p><small>Orden der stillen Wacht · Gott der Dichtung „Adahr“</small></section><section className="restDock"><div><span>RAST & ERHOLUNG</span><p>Bereit für das nächste Abenteuer?</p></div><button onClick={()=>rest('short')}><i>☕</i><span><b>Short Rest</b><small>Kurze Rast</small></span></button><button className="longRest" onClick={()=>rest('long')}><i>☾</i><span><b>Long Rest</b><small>TP vollständig auffüllen</small></span></button></section><button className="storyArea" onClick={()=>onNavigate('Notizen')} aria-label="Abenteuer und Story öffnen"><span>Abenteuer öffnen</span></button>{notice&&<div className="restToast" role="status">✓ {notice}</div>}</main>
}
