'use client';
import { useEffect, useMemo, useState } from 'react';
type Tab='Übersicht'|'Kampf'|'Zauber'|'Inventar'|'Notizen';
const abilities=[['STÄ',11,0],['GES',14,2],['KON',16,3],['INT',13,1],['WEI',9,-1],['CHA',15,2]];
const skills=[['Akrobatik','+2'],['Mit Tieren umgehen','−1'],['Arkane Kunde','+3 ★'],['Athletik','+2'],['Täuschen','+2'],['Geschichte','+1'],['Motiv erkennen','+1 ★'],['Einschüchtern','+2'],['Nachforschungen','+1'],['Heilkunde','−1'],['Naturkunde','+1'],['Wahrnehmung','−1'],['Auftreten','+2'],['Überzeugen','+4 ★'],['Religion','+1'],['Fingerfertigkeit','+2'],['Heimlichkeit','+2'],['Überleben','−1']];
const features=[
 {name:'Göttliches Gespür',uses:3,note:'Innerhalb 20 m Celestials, Fiends und Untote erspüren; geweihte/entweihte Orte erkennen. Erneuert nach langer Rast.'},
 {name:'Handauflegen',uses:15,note:'Trefferpunkte heilen; 5 Punkte können eine Krankheit oder ein Gift neutralisieren. Erneuert nach langer Rast.'},
 {name:'Kampfstil: Große Waffen',uses:0,note:'Bei einer 1 oder 2 auf einem Schadenswürfel darf dieser erneut gewürfelt werden.'},
 {name:'Göttliche Macht fokussieren',uses:2,note:'Wie Zauber nutzbar; Beispiele auf dem Blatt: Athletik und inspirierendes Niederstrecken.'},
];
const spells=[
 {name:'Göttliche Gunst',kind:'Bonusaktion',detail:'+2W8 zusätzlicher Schaden',uncertain:true},
 {name:'Segnen',kind:'Aktion · Konzentration',detail:'+1W4 für drei Verbündete, 10 Runden'},
 {name:'Befehl',kind:'Aktion',detail:'Ein Wort: Schlaf, Knie, Handstand, Lüge …',uncertain:true},
 {name:'Heldenmut',kind:'Aktion · Konzentration',detail:'Immun gegen Verängstigt; temporäre TP in Höhe des Charisma-Bonus'},
 {name:'Lenkendes Geschoss',kind:'Aktion',detail:'36 m, 4W6; nächster Angriff gegen das Ziel im Vorteil'},
];
const inventory=['Rucksack','Schlafsack','Essgeschirr','Feuerdose','10 Fackeln','Proviant für 13 Tage','Wasserschlauch','15 m Hanfseil','Diverse Schriftrollen (Elfisch) – gestohlen','2 grüne Tränke (Wirkung unklar)','5 Nachtsichttropfen (je 30 Min.)','1 Heiltrank (W8)','Grubenkriecher (tot)','Wabernder Armreif im Schädel','Ring – hebt bis Taubser Fluch auf','1 weißer Glücksstein'];
const questions=['Heißt der Charakter „Thartos“?','Ist die Gesinnung „Neutral / Rebel Moral“ oder etwas anderes?','Ist die Bewegungsrate 10 Meter?','Ist der Angriff mit dem Speer +4 und der Schaden 1W6 (einhändig) / 1W8 (zweihändig)?','Bei „Göttliche Gunst“: Steht dort wirklich +2W8 zusätzlicher Schaden?','Was genau bewirkt der Ring („bis Taubser Fluch aufhebt“)?','Wie lautet der abgeschnittene Text bei „Herausforderung des Wächters“?'];
export default function Home(){
 const[tab,setTab]=useState<Tab>('Übersicht');const[hp,setHp]=useState(29);const[tempHp,setTempHp]=useState(5);const[slots,setSlots]=useState([false,false]);const[search,setSearch]=useState('');const[dark,setDark]=useState(false);const[ready,setReady]=useState(false);
 // Initial restoration is intentionally client-only; the photographed sheet values remain the SSR fallback.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{const saved=localStorage.getItem('thartos-state');if(saved){try{const v=JSON.parse(saved);setHp(v.hp??29);setTempHp(v.tempHp??5);setSlots(v.slots??[false,false]);setDark(v.dark??false)}catch{}}setReady(true)},[]);
 useEffect(()=>{if(ready)localStorage.setItem('thartos-state',JSON.stringify({hp,tempHp,slots,dark}))},[hp,tempHp,slots,dark,ready]);
 const filtered=useMemo(()=>inventory.filter(x=>x.toLowerCase().includes(search.toLowerCase())),[search]);
 return <main className={dark?'app dark':'app'}><header className="topbar"><button className="brand" onClick={()=>setTab('Übersicht')} aria-label="Zur Übersicht"><span className="brandMark">T</span><span><strong>Thartos</strong><small>Charakterbogen</small></span></button><nav aria-label="Hauptnavigation">{(['Übersicht','Kampf','Zauber','Inventar','Notizen'] as Tab[]).map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</nav><button className="iconButton" onClick={()=>setDark(!dark)} aria-label="Farbschema wechseln">{dark?'☀':'☾'}</button></header>
 <section className="hero"><div><p className="eyebrow">MENSCH · PALADIN III</p><h1>Thartos <span className="uncertain">?</span></h1><p className="subline">Neutral / „Rebel Moral“ <span className="uncertain">unklar</span> · Spieler: Tobi</p></div><div className="heroStats"><Stat label="Rüstung" value="16"/><Stat label="Initiative" value="+2"/><Stat label="Tempo" value="10?"/><Stat label="Übung" value="+2"/></div></section>
 {tab==='Übersicht'&&<Overview {...{hp,setHp,tempHp,setTempHp,slots,setSlots}}/>}{tab==='Kampf'&&<Combat {...{hp,setHp,tempHp,setTempHp}}/>}{tab==='Zauber'&&<Spells {...{slots,setSlots}}/>}{tab==='Inventar'&&<Inventory search={search} setSearch={setSearch} items={filtered}/>} {tab==='Notizen'&&<Notes/>}<footer><span>Aus Fotos & Live Photo übertragen</span><span><i/> Unklare Abschrift bewusst markiert</span></footer></main>}
function Stat({label,value}:{label:string;value:string}){return <div className="stat"><strong>{value}</strong><span>{label}</span></div>}
type Health={hp:number;setHp:(n:number)=>void;tempHp:number;setTempHp:(n:number)=>void};
function HpCard({hp,setHp,tempHp,setTempHp}:Health){return <section className="card healthCard"><div className="cardHead"><span className="kicker">LEBENSPUNKTE</span><span className="maxHp">MAX. 29</span></div><div className="hpRing" style={{'--hp':`${Math.max(0,Math.min(100,hp/29*100))}%`} as React.CSSProperties}><strong>{hp}</strong><span>/ 29</span></div><div className="stepper"><button onClick={()=>setHp(Math.max(0,hp-1))}>−</button><button className="heal" onClick={()=>setHp(Math.min(29,hp+1))}>+ Heilen</button><button onClick={()=>setHp(Math.min(29,hp+1))}>+</button></div><label className="tempRow">Temporär <button onClick={()=>setTempHp(Math.max(0,tempHp-1))}>−</button><strong>{tempHp}</strong><button onClick={()=>setTempHp(tempHp+1)}>+</button></label></section>}
function Overview({hp,setHp,tempHp,setTempHp,slots,setSlots}:Health&{slots:boolean[];setSlots:(n:boolean[])=>void}){return <div className="content gridOverview"><div className="stack"><HpCard {...{hp,setHp,tempHp,setTempHp}}/><section className="card"><div className="cardHead"><span className="kicker">ATTRIBUTSWERTE</span><span className="muted">Rettungswürfe ★ WEI, CHA</span></div><div className="abilities">{abilities.map(([n,s,m])=><div key={n}><span>{n}</span><strong>{Number(m)>=0?'+':''}{m}</strong><small>{s}</small></div>)}</div></section></div><div className="stack"><section className="card"><div className="cardHead"><span className="kicker">SCHNELLZUGRIFF</span><span className="statusDot">SPIELBEREIT</span></div><div className="actions"><Action icon="⚔" title="Langschwert" meta="+2 · 1W8+0"/><Action icon="➶" title="Speer" meta="+4 · 1W6 / 1W8 ?" uncertain/><Action icon="✦" title="Handauflegen" meta="15 Punkte"/></div></section><section className="card"><div className="cardHead"><span className="kicker">ZAUBERPLÄTZE · GRAD 1</span><span className="muted">SG 12 · Angriff +4</span></div><SlotControl {...{slots,setSlots}}/><div className="spellPreview">{spells.slice(0,3).map(s=><div key={s.name}><strong>{s.name}{s.uncertain&&<span className="uncertain">?</span>}</strong><span>{s.kind}</span></div>)}</div></section></div><div className="stack"><section className="card"><div className="cardHead"><span className="kicker">FERTIGKEITEN</span><span className="muted">★ geübt</span></div><div className="skillList">{skills.map(([n,v])=><div key={n}><span>{n}</span><strong>{v}</strong></div>)}</div></section><section className="card warning"><div className="cardHead"><span className="kicker">NOCH ZU KLÄREN</span><span className="questionCount">{questions.length}</span></div><p>{questions[0]}</p><p>{questions[1]}</p><button onClick={()=>setTimeout(()=>document.getElementById('questions')?.scrollIntoView({behavior:'smooth'}),0)}>Alle Fragen in Notizen →</button></section></div></div>}
function Action({icon,title,meta,uncertain=false}:{icon:string;title:string;meta:string;uncertain?:boolean}){return <div className="action"><span>{icon}</span><div><strong>{title}{uncertain&&<em>?</em>}</strong><small>{meta}</small></div><button aria-label={`${title} würfeln`}>W20</button></div>}
function SlotControl({slots,setSlots}:{slots:boolean[];setSlots:(n:boolean[])=>void}){return <div className="slots">{slots.map((used,i)=><button key={i} className={used?'used':''} onClick={()=>setSlots(slots.map((s,j)=>j===i?!s:s))}>{used?'×':'◇'}</button>)}<span>{slots.filter(Boolean).length} / 2 verbraucht</span><button className="restore" onClick={()=>setSlots([false,false])}>Rast</button></div>}
function Combat(p:Health){return <div className="content twoCol"><div className="stack"><HpCard {...p}/><section className="card"><div className="cardHead"><span className="kicker">ANGRIFFE</span></div><div className="actions large"><Action icon="⚔" title="Langschwert" meta="Angriff +2 · Schaden 1W8+0"/><Action icon="➶" title="Speer" meta="Angriff +4 · 1W6 / 1W8 ?" uncertain/><Action icon="✧" title="Silberschwert" meta="+1 auf Angriff & Schaden; +1 CHA bei Überschritt" uncertain/></div></section></div><div className="stack"><section className="card"><div className="cardHead"><span className="kicker">KLASSENMERKMALE</span></div><div className="featureList">{features.map(f=><article key={f.name}><div><strong>{f.name}</strong>{f.uses>0&&<span>{f.uses}×</span>}</div><p>{f.note}</p></article>)}</div></section><section className="card note"><span className="kicker">WEITERE KAMPFHINWEISE</span><p>„Knightly Regard“: Ich finde in Flammen meines Ordens häufig Zuflucht.</p><p>Jeder 4. Treffer misslingt → muss geworfen werden.</p></section></div></div>}
function Spells({slots,setSlots}:{slots:boolean[];setSlots:(n:boolean[])=>void}){return <div className="content twoCol spellsPage"><div className="stack"><section className="card spellHeader"><div><span className="kicker">ZAUBERWIRKEN</span><h2>Charisma</h2><p>Zauber-SG <b>12</b> · Angriffsbonus <b>+4</b></p></div><div className="sigil">✦</div></section><section className="card"><div className="cardHead"><span className="kicker">ZAUBERPLÄTZE · GRAD 1</span></div><SlotControl {...{slots,setSlots}}/></section></div><section className="card"><div className="cardHead"><span className="kicker">BEKANNTE ZAUBER</span><span className="muted">Grad 1</span></div><div className="spellList">{spells.map(s=><article key={s.name}><div><strong>{s.name}{s.uncertain&&<span className="uncertain">?</span>}</strong><span>{s.kind}</span></div><p>{s.detail}</p></article>)}</div></section></div>}
function Inventory({search,setSearch,items}:{search:string;setSearch:(n:string)=>void;items:string[]}){return <div className="content twoCol"><section className="card"><div className="cardHead"><span className="kicker">AUSRÜSTUNG</span><span className="muted">{inventory.length} Einträge</span></div><input className="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Ausrüstung suchen …"/><div className="inventory">{items.map((x,i)=><div key={x}><span>{String(i+1).padStart(2,'0')}</span><strong>{x}</strong>{x.includes('unklar')||x.includes('Taubser')?<em>?</em>:null}</div>)}</div></section><div className="stack"><section className="card"><div className="cardHead"><span className="kicker">GELD</span></div><div className="coins"><div><strong>8</strong><span>KM</span></div><div><strong>0</strong><span>SM</span></div><div><strong>48</strong><span>GM</span></div></div></section><section className="card"><div className="cardHead"><span className="kicker">WEITERE BESITZTÜMER</span></div><p>Langschwert + Langschwert, 5 Speere, Kettenrüstung, Heiliges Symbol (polierter runder/flacher Stein mit eingeritzter Inschrift), Banner.</p></section><section className="card"><div className="cardHead"><span className="kicker">SPRACHEN & ÜBUNG</span></div><p>Rüstungen: alle · Waffen: alle · Schach</p><p>Sprachen: Zwergisch, Halbling</p></section></div></div>}
function Notes(){return <div className="content twoCol"><section className="card" id="questions"><div className="cardHead"><span className="kicker">OFFENE FRAGEN</span><span className="questionCount">{questions.length}</span></div><p className="intro">Diese Stellen waren auf den Vorlagen nicht eindeutig. Es wurde nichts ergänzt oder geraten.</p><ol className="questions">{questions.map(q=><li key={q}><span>?</span>{q}</li>)}</ol></section><div className="stack"><section className="card"><div className="cardHead"><span className="kicker">BINDUNG</span></div><p>Gott der Dichtung: Adahr <span className="uncertain">?</span></p></section><section className="card"><div className="cardHead"><span className="kicker">WEITERE NOTIZEN</span></div><p>Immunität gegen Krankheiten.</p><p>„Herausforderung des Wächters“: Gegner macht Rettungswurf; Rest des Hinweises ist abgeschnitten.</p><p>Wabernder Armreif: Schattenarmreif; als Bonusaktion innerhalb 30 m springen.</p></section><section className="card source"><div className="cardHead"><span className="kicker">QUELLENSTATUS</span></div><p>Hauptbogen aus dem Live Photo, Zauberbogen und Inventar aus den beiden Fotos.</p><span className="verified">✓ Lesbare Werte übernommen</span></section></div></div>}
